/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import controlador.ControladorDailyDairy;

import javax.swing.*;
import java.awt.*;

/**
 *
 * @author Uriel Méndez Romero
 */
public class PanelGanado extends javax.swing.JPanel {

  /**
   * Creates new form PanelGanado
   */
  public PanelGanado() {
    initComponents();
  }

  public JPanel getBtnAgregar() {
    return btnAgregar;
  }

  public JPanel getBtnEditar() {
    return btnEditar;
  }

  public JPanel getBtnEliminar() {
    return btnEliminar;
  }

//  public JPanel getBtnListaGanado() {
//    return btnListaGanado;
//  }

  public JPanel getBtnMostrarOrdena() {
    return btnMostrarOrdena;
  }

  public JButton getBtnRegresar() {
    return btnRegresar;
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    panelIzquierda = new javax.swing.JPanel();
    btnAgregar = new javax.swing.JPanel();
    lblTituloAgregar = new javax.swing.JLabel();
    lblSubAgregar = new javax.swing.JLabel();
    btnEliminar = new javax.swing.JPanel();
    lblTituloEliminar = new javax.swing.JLabel();
    lblSubEliminar = new javax.swing.JLabel();
    btnEditar = new javax.swing.JPanel();
    lblTituloEditar = new javax.swing.JLabel();
    lblSubEditar = new javax.swing.JLabel();
//    btnListaGanado = new javax.swing.JPanel();
    lblTituloListaGanado = new javax.swing.JLabel();
    lblSubListaGanado = new javax.swing.JLabel();
    btnMostrarOrdena = new javax.swing.JPanel();
    lblTituloMostrarOrdena = new javax.swing.JLabel();
    lblSubMostrarOrdena = new javax.swing.JLabel();
    panelDerecha = new javax.swing.JPanel();
    panelNorte = new javax.swing.JPanel();
    lblTituloGanadoExistente = new javax.swing.JLabel();
    panelCentro = new javax.swing.JPanel();
    panelTablaGanado = new javax.swing.JScrollPane();
    tablaGanado = new javax.swing.JTable();
    panelImagenGanado = new javax.swing.JPanel();
    lblImagenGanado = new javax.swing.JLabel();
    panelSur = new javax.swing.JPanel();
    btnRegresar = new javax.swing.JButton();

    setBackground(new Color(254, 254, 254));
    setBorder(new javax.swing.border.LineBorder(new Color(255, 255, 255), 10, true));
    setLayout(new java.awt.BorderLayout(5, 5));

    panelIzquierda.setPreferredSize(new Dimension(240,573));
    panelIzquierda.setBackground(new Color(143,190,0,170));
    panelIzquierda.setBorder(javax.swing.BorderFactory.createEmptyBorder(40, 40, 40, 40));
    panelIzquierda.setLayout(new java.awt.GridLayout(4, 1, 20, 20));

    btnAgregar.setBackground(new Color(0, 168, 198, 135));
    btnAgregar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
//    //btnAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
//      public void mouseClicked(java.awt.event.MouseEvent evt) {
//        Clic(evt);
//      }
//    });
    btnAgregar.setLayout(new java.awt.GridLayout(2, 0));

    lblTituloAgregar.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
    lblTituloAgregar.setForeground(new Color(255, 255, 255));
    lblTituloAgregar.setText("Agregar");
    lblTituloAgregar.setToolTipText("");
    lblTituloAgregar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
    lblTituloAgregar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
    lblTituloAgregar.setFocusable(false);
    lblTituloAgregar.setPreferredSize(new java.awt.Dimension(62, 20));
    btnAgregar.add(lblTituloAgregar);

    lblSubAgregar.setFont(new java.awt.Font("Corbel", 0, 12)); // NOI18N
    lblSubAgregar.setForeground(new Color(255, 255, 255));
    lblSubAgregar.setText("<html><body>Agregar nuevo ganado</body></html>");
    lblSubAgregar.setVerticalAlignment(javax.swing.SwingConstants.TOP);
    lblSubAgregar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
    lblSubAgregar.setFocusable(false);
    lblSubAgregar.setPreferredSize(new java.awt.Dimension(100, 18));
    btnAgregar.add(lblSubAgregar);

    panelIzquierda.add(btnAgregar);

    btnEliminar.setBackground(new Color(0, 168, 198, 135));
    btnEliminar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
    btnEliminar.setLayout(new java.awt.GridLayout(2, 1));

    lblTituloEliminar.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
    lblTituloEliminar.setForeground(new Color(255, 255, 255));
    lblTituloEliminar.setText("Eliminar");
    lblTituloEliminar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
    lblTituloEliminar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
    lblTituloEliminar.setPreferredSize(new java.awt.Dimension(63, 20));
    btnEliminar.add(lblTituloEliminar);

    lblSubEliminar.setFont(new java.awt.Font("Corbel", 0, 12)); // NOI18N
    lblSubEliminar.setForeground(new Color(255, 255, 255));
    lblSubEliminar.setText("<html><body>Eliminar ganado</body></html>");
    lblSubEliminar.setToolTipText("");
    lblSubEliminar.setVerticalAlignment(javax.swing.SwingConstants.TOP);
    lblSubEliminar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
    lblSubEliminar.setPreferredSize(new java.awt.Dimension(100, 18));
    btnEliminar.add(lblSubEliminar);

    panelIzquierda.add(btnEliminar);

    btnEditar.setBackground(new Color(0, 168, 198, 135));
    btnEditar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
    btnEditar.setLayout(new java.awt.GridLayout(2, 1));

    lblTituloEditar.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
    lblTituloEditar.setForeground(new Color(255, 255, 255));
    lblTituloEditar.setText("Editar");
    lblTituloEditar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
    lblTituloEditar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
    lblTituloEditar.setMaximumSize(new java.awt.Dimension(55, 18));
    lblTituloEditar.setMinimumSize(new java.awt.Dimension(55, 18));
    lblTituloEditar.setPreferredSize(new java.awt.Dimension(46, 20));
    btnEditar.add(lblTituloEditar);

    lblSubEditar.setFont(new java.awt.Font("Corbel", 0, 12)); // NOI18N
    lblSubEditar.setForeground(new Color(255, 255, 255));
    lblSubEditar.setText("<html><body>Modificar ganado existente </body></html>");
    lblSubEditar.setVerticalAlignment(javax.swing.SwingConstants.TOP);
    lblSubEditar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
    lblSubEditar.setPreferredSize(new java.awt.Dimension(100, 18));
    btnEditar.add(lblSubEditar);

    panelIzquierda.add(btnEditar);

    /*btnListaGanado.setBackground(new Color(0, 168, 198, 135));
    btnListaGanado.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
    btnListaGanado.setLayout(new java.awt.GridLayout(2, 1));

    lblTituloListaGanado.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
    lblTituloListaGanado.setForeground(new Color(255, 255, 255));
    lblTituloListaGanado.setText("Lista de ganado");
    lblTituloListaGanado.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
    lblTituloListaGanado.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
    lblTituloListaGanado.setPreferredSize(new java.awt.Dimension(123, 20));
    btnListaGanado.add(lblTituloListaGanado);

    lblSubListaGanado.setFont(new java.awt.Font("Corbel", 0, 12)); // NOI18N
    lblSubListaGanado.setForeground(new Color(255, 255, 255));
    lblSubListaGanado.setText("<html><body>Genera una lista del ganado existente </body></html>");
    lblSubListaGanado.setVerticalAlignment(javax.swing.SwingConstants.TOP);
    lblSubListaGanado.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
    lblSubListaGanado.setPreferredSize(new java.awt.Dimension(100, 18));
    btnListaGanado.add(lblSubListaGanado);

    panelIzquierda.add(btnListaGanado);*/

    btnMostrarOrdena.setBackground(new Color(0, 168, 198, 135));
    btnMostrarOrdena.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
    btnMostrarOrdena.setLayout(new java.awt.GridLayout(2, 0));

    lblTituloMostrarOrdena.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
    lblTituloMostrarOrdena.setForeground(new Color(255, 255, 255));
    lblTituloMostrarOrdena.setText("Mostrar ordeña");
    lblTituloMostrarOrdena.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
    lblTituloMostrarOrdena.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
    btnMostrarOrdena.add(lblTituloMostrarOrdena);

    lblSubMostrarOrdena.setFont(new java.awt.Font("Corbel", 0, 12)); // NOI18N
    lblSubMostrarOrdena.setForeground(new Color(255, 255, 255));
    lblSubMostrarOrdena.setText("Mostar interfaz de ordeña");
    lblSubMostrarOrdena.setVerticalAlignment(javax.swing.SwingConstants.TOP);
    lblSubMostrarOrdena.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
    btnMostrarOrdena.add(lblSubMostrarOrdena);

    panelIzquierda.add(btnMostrarOrdena);

    add(panelIzquierda, java.awt.BorderLayout.LINE_START);

    panelDerecha.setLayout(new java.awt.BorderLayout());

    panelNorte.setBackground(new Color(143,190,0,25));
    panelNorte.setBorder(javax.swing.BorderFactory.createEmptyBorder(40, 20, 20, 20));

    lblTituloGanadoExistente.setFont(new java.awt.Font("Corbel", 1, 24)); // NOI18N
    lblTituloGanadoExistente.setText("GANADO EXISTENTE");
    panelNorte.add(lblTituloGanadoExistente);

    panelDerecha.add(panelNorte, java.awt.BorderLayout.PAGE_START);

    panelCentro.setBackground(new Color(143,190,0,25));
    panelCentro.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 40, 40, 10));
    panelCentro.setLayout(new java.awt.BorderLayout());

    tablaGanado.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {
        /*{null, null, null, null, null, null},
        {null, null, null, null, null, null},
        {null, null, null, null, null, null},
        {null, null, null, null, null, null}*/
      },
      new String [] {
        "NUMERO", "FIERRO", "COLOR", "RAZA", "DESCRIPCION", "SEXO"
      }
    ) {
      Class[] types = new Class [] {
        String.class, String.class, String.class, String.class, Object.class, Object.class, Object.class
      };

      public Class getColumnClass(int columnIndex) {
        return types [columnIndex];
      }
    });
    panelTablaGanado.setViewportView(tablaGanado);

    panelCentro.add(panelTablaGanado, java.awt.BorderLayout.CENTER);

    panelImagenGanado.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
    panelImagenGanado.setOpaque(false);
    panelImagenGanado.setLayout(new java.awt.BorderLayout());

    lblImagenGanado.setBackground(new java.awt.Color(204, 204, 204));
    lblImagenGanado.setMaximumSize(new java.awt.Dimension(200, 150));
    lblImagenGanado.setMinimumSize(new java.awt.Dimension(200, 150));
    lblImagenGanado.setPreferredSize(new java.awt.Dimension(200, 150));
    panelImagenGanado.add(lblImagenGanado, java.awt.BorderLayout.CENTER);

    panelCentro.add(panelImagenGanado, java.awt.BorderLayout.LINE_END);


    panelDerecha.add(panelCentro, java.awt.BorderLayout.CENTER);

    panelSur.setBackground(new Color(143,190,0,25));
    panelSur.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 20, 1));

    btnRegresar.setBackground(new Color(0, 168, 198, 135));
    btnRegresar.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
    btnRegresar.setForeground(new Color(255, 255, 255));
    btnRegresar.setText("Regresar");
    btnRegresar.setFocusPainted(false);
    btnRegresar.setFocusable(false);
    btnRegresar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    btnRegresar.setMargin(new java.awt.Insets(4, 14, 4, 14));
    panelSur.add(btnRegresar);

    panelDerecha.add(panelSur, java.awt.BorderLayout.SOUTH);

    add(panelDerecha, java.awt.BorderLayout.CENTER);
  }// </editor-fold>//GEN-END:initComponents

  private void Clic(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Clic
    System.out.println("Cliclekd");    
    
  }//GEN-LAST:event_Clic


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel btnAgregar;
  private javax.swing.JPanel btnEditar;
  private javax.swing.JPanel btnEliminar;
//  private javax.swing.JPanel btnListaGanado;
  private javax.swing.JPanel btnMostrarOrdena;
  private javax.swing.JButton btnRegresar;
  private javax.swing.JLabel lblSubAgregar;
  private javax.swing.JLabel lblSubEditar;
  private javax.swing.JLabel lblSubEliminar;
  private javax.swing.JLabel lblSubListaGanado;
  private javax.swing.JLabel lblSubMostrarOrdena;
  private javax.swing.JLabel lblTituloAgregar;
  private javax.swing.JLabel lblTituloEditar;
  private javax.swing.JLabel lblTituloEliminar;
  private javax.swing.JLabel lblTituloGanadoExistente;
  private javax.swing.JLabel lblTituloListaGanado;
  private javax.swing.JLabel lblTituloMostrarOrdena;
  private javax.swing.JPanel panelCentro;
  private javax.swing.JPanel panelDerecha;
  private javax.swing.JPanel panelIzquierda;
  private javax.swing.JPanel panelNorte;
  private javax.swing.JPanel panelSur;
  private javax.swing.JScrollPane panelTablaGanado;
  private javax.swing.JTable tablaGanado;
  private javax.swing.JPanel panelImagenGanado;
  private javax.swing.JLabel lblImagenGanado;

  private ControladorDailyDairy controladorDailyDairy;
  public ControladorDailyDairy getControladorDailyDairy() {
    return controladorDailyDairy;
  }

  public JLabel getLblSubAgregar() {
    return lblSubAgregar;
  }

  public void setLblSubAgregar(JLabel lblSubAgregar) {
    this.lblSubAgregar = lblSubAgregar;
  }

  public JLabel getLblSubEditar() {
    return lblSubEditar;
  }

  public void setLblSubEditar(JLabel lblSubEditar) {
    this.lblSubEditar = lblSubEditar;
  }

  public JLabel getLblSubEliminar() {
    return lblSubEliminar;
  }

  public void setLblSubEliminar(JLabel lblSubEliminar) {
    this.lblSubEliminar = lblSubEliminar;
  }

  public JLabel getLblSubListaGanado() {
    return lblSubListaGanado;
  }

  public void setLblSubListaGanado(JLabel lblSubListaGanado) {
    this.lblSubListaGanado = lblSubListaGanado;
  }

  public JLabel getLblSubMostrarOrdena() {
    return lblSubMostrarOrdena;
  }

  public void setLblSubMostrarOrdena(JLabel lblSubMostrarOrdena) {
    this.lblSubMostrarOrdena = lblSubMostrarOrdena;
  }

  public JLabel getLblTituloAgregar() {
    return lblTituloAgregar;
  }

  public void setLblTituloAgregar(JLabel lblTituloAgregar) {
    this.lblTituloAgregar = lblTituloAgregar;
  }

  public JLabel getLblTituloEditar() {
    return lblTituloEditar;
  }

  public void setLblTituloEditar(JLabel lblTituloEditar) {
    this.lblTituloEditar = lblTituloEditar;
  }

  public JLabel getLblTituloEliminar() {
    return lblTituloEliminar;
  }

  public void setLblTituloEliminar(JLabel lblTituloEliminar) {
    this.lblTituloEliminar = lblTituloEliminar;
  }

  public JLabel getLblTituloListaGanado() {
    return lblTituloListaGanado;
  }

  public void setLblTituloListaGanado(JLabel lblTituloListaGanado) {
    this.lblTituloListaGanado = lblTituloListaGanado;
  }

  public JLabel getLblTituloMostrarOrdena() {
    return lblTituloMostrarOrdena;
  }

  public void setLblTituloMostrarOrdena(JLabel lblTituloMostrarOrdena) {
    this.lblTituloMostrarOrdena = lblTituloMostrarOrdena;
  }

  public JTable getTablaGanado() {
    return tablaGanado;
  }

  public void setTablaGanado(JTable tablaGanado) {
    this.tablaGanado = tablaGanado;
  }

  public void setControlador(ControladorDailyDairy controladorDailyDairy) {
    this.controladorDailyDairy = controladorDailyDairy;
    this.btnRegresar.addActionListener(this.controladorDailyDairy);
    this.btnAgregar.addMouseListener(this.controladorDailyDairy);
    this.btnEliminar.addMouseListener(this.controladorDailyDairy);
    this.btnEditar.addMouseListener(this.controladorDailyDairy);
//    this.btnListaGanado.addMouseListener(this.controladorDailyDairy);
    this.btnMostrarOrdena.addMouseListener(this.controladorDailyDairy);

    this.lblSubAgregar.addMouseListener(this.controladorDailyDairy);
    this.lblTituloAgregar.addMouseListener(this.controladorDailyDairy);
    this.lblSubEditar.addMouseListener(this.controladorDailyDairy);
    this.lblTituloEditar.addMouseListener(this.controladorDailyDairy);
    this.lblSubEliminar.addMouseListener(this.controladorDailyDairy);
    this.lblTituloEliminar.addMouseListener(this.controladorDailyDairy);
    this.lblSubMostrarOrdena.addMouseListener(this.controladorDailyDairy);
    this.lblTituloMostrarOrdena.addMouseListener(this.controladorDailyDairy);
    this.lblSubListaGanado.addMouseListener(this.controladorDailyDairy);
    this.lblTituloListaGanado.addMouseListener(this.controladorDailyDairy);

  }
  // End of variables declaration//GEN-END:variables
}
