/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import controlador.ControladorDailyDairy;
import modelo.InteractivePanel;
import modelo.VacasDailyDairy;

import javax.imageio.ImageIO;
import javax.swing.*;
import java.awt.Color;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.Blob;

/**
 *
 * @author Uriel Méndez Romero
 */
public class PanelAgregar extends javax.swing.JPanel implements InteractivePanel {

  /**
   * Creates new form PanelAgregar
   */
  public PanelAgregar() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelIzquierda = new javax.swing.JPanel();
        btnSelecImagen = new javax.swing.JPanel();
        lblTituloSelec = new javax.swing.JLabel();
        lblSubSelec = new javax.swing.JLabel();
        lblImagenGanado = new javax.swing.JLabel();
        panelEliminarImagen = new javax.swing.JPanel();
        btnEliminarImagen = new javax.swing.JButton();
        panelDerecha = new javax.swing.JPanel();
        panelSur = new javax.swing.JPanel();
        btnAgregar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        panelNorte = new javax.swing.JPanel();
        lblTituloRegistro = new javax.swing.JLabel();
        panelCentro = new javax.swing.JPanel();
        lblNumero = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        lblFierro = new javax.swing.JLabel();
        txtFierro = new javax.swing.JTextField();
        lblColor = new javax.swing.JLabel();
        txtColor = new javax.swing.JTextField();
        lblRaza = new javax.swing.JLabel();
        txtRaza = new javax.swing.JTextField();
        lblDescripcion = new javax.swing.JLabel();
        cboxDescripcion = new javax.swing.JComboBox<>();
        lblSexo = new javax.swing.JLabel();
        cboxSexo = new javax.swing.JComboBox<>();

        setBackground(new Color(254, 254, 254));
        setBorder(new javax.swing.border.LineBorder(new Color(255, 255, 255), 10, true));
        setLayout(new java.awt.BorderLayout(5, 0));

        panelIzquierda.setBackground(new Color(143,190,0,170));
        panelIzquierda.setBorder(javax.swing.BorderFactory.createEmptyBorder(30, 20, 20, 20));
        panelIzquierda.setLayout(new java.awt.GridLayout(3, 0, 0, 50));

        btnSelecImagen.setBackground(new Color(0, 168, 198, 135));
        btnSelecImagen.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSelecImagen.setLayout(new java.awt.GridLayout(2, 0));

        lblTituloSelec.setFont(new java.awt.Font("Corbel", 1, 20)); // NOI18N
        lblTituloSelec.setForeground(new Color(255, 255, 255));
        lblTituloSelec.setText("Seleccionar imagen");
        lblTituloSelec.setHorizontalAlignment(SwingConstants.CENTER);
        lblTituloSelec.setToolTipText("");
        lblTituloSelec.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lblTituloSelec.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        lblTituloSelec.setPreferredSize(new java.awt.Dimension(150, 20));
        btnSelecImagen.add(lblTituloSelec);

        lblSubSelec.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        lblSubSelec.setForeground(new Color(255, 255, 255));
        lblSubSelec.setText("<html>Seleccione la imagen del ganado</html>");
        lblSubSelec.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblSubSelec.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        lblSubSelec.setPreferredSize(new java.awt.Dimension(100, 18));
        btnSelecImagen.add(lblSubSelec);
        panelIzquierda.add(btnSelecImagen);

        lblImagenGanado.setToolTipText("");
        lblImagenGanado.setMaximumSize(new java.awt.Dimension(200, 150));
        lblImagenGanado.setMinimumSize(new java.awt.Dimension(200, 150));
        lblImagenGanado.setPreferredSize(new java.awt.Dimension(200, 150));
        lblImagenGanado.setRequestFocusEnabled(false);
        panelIzquierda.add(lblImagenGanado);

        panelEliminarImagen.setOpaque(false);

        btnEliminarImagen.setBackground(new Color(0, 168, 198, 135));
        btnEliminarImagen.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        btnEliminarImagen.setForeground(new Color(255, 255, 255));
        btnEliminarImagen.setText("Eliminar imagen");
        btnEliminarImagen.setFocusable(false);
        panelEliminarImagen.add(btnEliminarImagen);

        panelIzquierda.add(panelEliminarImagen);

        add(panelIzquierda, java.awt.BorderLayout.LINE_START);

        panelDerecha.setLayout(new java.awt.BorderLayout());

        panelSur.setBackground(new Color(143,190,0,25));
        panelSur.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 40, 5));
        panelSur.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 5));

        btnAgregar.setBackground(new Color(0, 168, 198, 135));
        btnAgregar.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        btnAgregar.setForeground(new Color(255, 255, 255));
        btnAgregar.setText("Agregar");
        btnAgregar.setFocusable(false);
        panelSur.add(btnAgregar);

        btnRegresar.setBackground(new Color(0, 168, 198, 135));
        btnRegresar.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        btnRegresar.setForeground(new Color(255, 255, 255));
        btnRegresar.setText("Regresar");
        panelSur.add(btnRegresar);

        panelDerecha.add(panelSur, java.awt.BorderLayout.PAGE_END);

        panelNorte.setBackground(new Color(143,190,0,25));
        panelNorte.setBorder(javax.swing.BorderFactory.createEmptyBorder(40, 20, 20, 20));

        lblTituloRegistro.setFont(new java.awt.Font("Corbel", 1, 24)); // NOI18N
        lblTituloRegistro.setText("REGISTRO DE GANADO");
        panelNorte.add(lblTituloRegistro);

        panelDerecha.add(panelNorte, java.awt.BorderLayout.NORTH);

        panelCentro.setBackground(new Color(143,190,0,25));
        panelCentro.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 110, 10, 110));
        panelCentro.setFocusable(false);
        panelCentro.setLayout(new java.awt.GridLayout(12, 0, 0, 5));

        lblNumero.setFont(new java.awt.Font("Corbel", 1, 16)); // NOI18N
        lblNumero.setText("Numero");
        lblNumero.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        panelCentro.add(lblNumero);

        txtNumero.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        txtNumero.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNumero.setPreferredSize(new java.awt.Dimension(64, 18));
        panelCentro.add(txtNumero);

        lblFierro.setFont(new java.awt.Font("Corbel", 1, 16)); // NOI18N
        lblFierro.setText("Fierro");
        lblFierro.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        panelCentro.add(lblFierro);

        txtFierro.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        txtFierro.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtFierro.setPreferredSize(new java.awt.Dimension(64, 18));
        panelCentro.add(txtFierro);

        lblColor.setFont(new java.awt.Font("Corbel", 1, 16)); // NOI18N
        lblColor.setText("Color");
        lblColor.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        panelCentro.add(lblColor);

        txtColor.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        txtColor.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtColor.setPreferredSize(new java.awt.Dimension(64, 18));
        panelCentro.add(txtColor);

        lblRaza.setFont(new java.awt.Font("Corbel", 1, 16)); // NOI18N
        lblRaza.setText("Raza");
        lblRaza.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        panelCentro.add(lblRaza);

        txtRaza.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        txtRaza.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtRaza.setPreferredSize(new java.awt.Dimension(64, 18));
        panelCentro.add(txtRaza);

        lblDescripcion.setFont(new java.awt.Font("Corbel", 1, 16)); // NOI18N
        lblDescripcion.setText("Descripción");
        panelCentro.add(lblDescripcion);

        cboxDescripcion.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        cboxDescripcion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vaca", "Toro", "Novillo", "Novilla", "Vaquilla", "Cria" }));
        cboxDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxDescripcionActionPerformed(evt);
            }
        });
        panelCentro.add(cboxDescripcion);

        lblSexo.setFont(new java.awt.Font("Corbel", 1, 16)); // NOI18N
        lblSexo.setText("Sexo");
        lblSexo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        panelCentro.add(lblSexo);

        cboxSexo.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        cboxSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Macho", "Hembra" }));
        cboxSexo.setSelectedItem("");
        cboxSexo.setToolTipText("");
        panelCentro.add(cboxSexo);

        panelDerecha.add(panelCentro, java.awt.BorderLayout.CENTER);

        add(panelDerecha, java.awt.BorderLayout.CENTER);

      try {
          image = ImageIO.read(new File("src/main/resources/imagenes/vacaDefaultverde2.png"));
      } catch (IOException e) {
          throw new RuntimeException(e);
      }

  }// </editor-fold>//GEN-END:initComponents

    private void cboxDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboxDescripcionActionPerformed

    public JLabel getLblSubSelec() {
        return lblSubSelec;
    }

    public void setLblSubSelec(JLabel lblSubSelec) {
        this.lblSubSelec = lblSubSelec;
    }

    public JLabel getLblTituloSelec() {
        return lblTituloSelec;
    }

    public void setLblTituloSelec(JLabel lblTituloSelec) {
        this.lblTituloSelec = lblTituloSelec;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminarImagen;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JPanel btnSelecImagen;
    private javax.swing.JComboBox<String> cboxDescripcion;
    private javax.swing.JComboBox<String> cboxSexo;
    private javax.swing.JLabel lblColor;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblFierro;
    private javax.swing.JLabel lblImagenGanado;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblRaza;
    private javax.swing.JLabel lblSexo;
    private javax.swing.JLabel lblSubSelec;
    private javax.swing.JLabel lblTituloRegistro;
    private javax.swing.JLabel lblTituloSelec;
    private javax.swing.JPanel panelCentro;
    private javax.swing.JPanel panelDerecha;
    private javax.swing.JPanel panelEliminarImagen;
    private javax.swing.JPanel panelIzquierda;
    private javax.swing.JPanel panelNorte;
    private javax.swing.JPanel panelSur;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtFierro;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtRaza;

    public BufferedImage image;

    public JLabel getLblImagenGanado() {
        return lblImagenGanado;
    }

    public void setLblImagenGanado(JLabel lblImagenGanado) {
        this.lblImagenGanado = lblImagenGanado;
    }

    private ControladorDailyDairy controladorDailyDairy;
    public ControladorDailyDairy getControladorDailyDairy() {
        return controladorDailyDairy;
    }

    public void setControlador(ControladorDailyDairy controladorDailyDairy) {
        this.controladorDailyDairy = controladorDailyDairy;
        this.btnRegresar.addActionListener(this.controladorDailyDairy);
        this.btnAgregar.addActionListener(this.controladorDailyDairy);
        this.cboxDescripcion.addItemListener(this.controladorDailyDairy);
        //this.lblImagenGanado.addMouseListener(this.controladorDailyDairy);
        this.lblTituloSelec.addMouseListener(this.controladorDailyDairy);
        this.lblSubSelec.addMouseListener(this.controladorDailyDairy);
        this.btnAgregar.addMouseListener(this.controladorDailyDairy);
        this.btnEliminarImagen.addMouseListener(this.controladorDailyDairy);

    }

    public JButton getBtnRegresar() {
        return this.btnRegresar;
    }

    public JButton getBtnAgregar() {
    return this.btnAgregar;
    }
    // End of variables declaration//GEN-END:variables


    public void setBtnAgregar(JButton btnAgregar) {
        this.btnAgregar = btnAgregar;
    }

    public JButton getBtnEliminarImagen() {
        return btnEliminarImagen;
    }

    public void setBtnEliminarImagen(JButton btnEliminarImagen) {
        this.btnEliminarImagen = btnEliminarImagen;
    }

    public void setBtnRegresar(JButton btnRegresar) {
        this.btnRegresar = btnRegresar;
    }

    public JPanel getBtnSelecImagen() {
        return btnSelecImagen;
    }

    public void setBtnSelecImagen(JPanel btnSelecImagen) {
        this.btnSelecImagen = btnSelecImagen;
    }

    public JComboBox<String> getCboxDescripcion() {
        return cboxDescripcion;
    }

    public void setCboxDescripcion(JComboBox<String> cboxDescripcion) {
        this.cboxDescripcion = cboxDescripcion;
    }

    public JComboBox<String> getCboxSexo() {
        return cboxSexo;
    }

    public void setCboxSexo(JComboBox<String> cboxSexo) {
        this.cboxSexo = cboxSexo;
    }

    public JTextField getTxtColor() {
        return txtColor;
    }

    public void setTxtColor(JTextField txtColor) {
        this.txtColor = txtColor;
    }

    public JTextField getTxtFierro() {
        return txtFierro;
    }

    public void setTxtFierro(JTextField txtFierro) {
        this.txtFierro = txtFierro;
    }

    public JTextField getTxtNumero() {
        return txtNumero;
    }

    public void setTxtNumero(JTextField txtNumero) {
        this.txtNumero = txtNumero;
    }

    public JTextField getTxtRaza() {
        return txtRaza;
    }

    public void setTxtRaza(JTextField txtRaza) {
        this.txtRaza = txtRaza;
    }

    @Override
    public void refreshPanel() {

        lblImagenGanado.setIcon(new ImageIcon(image));
        revalidate();
        repaint();

        this.lblTituloSelec.repaint();

    }
}
