/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import controlador.ControladorDailyDairy;

import javax.swing.*;
import java.awt.Color;

/**
 *
 * @author Uriel Méndez Romero
 */
public class PanelProduccion extends javax.swing.JPanel {

  /**
   * Creates new form PanelProduccion
   */
  public PanelProduccion() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    panelPestanas = new javax.swing.JTabbedPane();
    panelRegistroProduccion = new javax.swing.JPanel();
    panelNorteRegistro = new javax.swing.JPanel();
    lblTituloRegistro = new javax.swing.JLabel();
    panelCentroRegistro = new javax.swing.JPanel();
    panelTablaRegistro = new javax.swing.JScrollPane();
    tablaRegistroProduccion = new javax.swing.JTable();
    panelSurRegistro = new javax.swing.JPanel();
    btnRegistrar = new javax.swing.JButton();
    btnRegresarFromRegistro = new javax.swing.JButton();
    panelConsultaProduccion = new javax.swing.JPanel();
    panelNorteConsulta = new javax.swing.JPanel();
    lblTituloConsulta = new javax.swing.JLabel();
    panelInputs = new javax.swing.JPanel();
    lblFechaInicio = new javax.swing.JLabel();
    txtFechaInicio = new javax.swing.JTextField();
    btnSelecFechaInicio = new javax.swing.JButton();
    lblFechaCierre = new javax.swing.JLabel();
    txtFechaCierre = new javax.swing.JTextField();
    btnSelecFechaCierre = new javax.swing.JButton();
    panelSurConsulta = new javax.swing.JPanel();
    btnGenerar = new javax.swing.JButton();
    btnRegresarFromConsulta = new javax.swing.JButton();
    panelCentroConsulta = new javax.swing.JPanel();
    panelTablaConsulta = new javax.swing.JScrollPane();
    tablaConsultaProduccion = new javax.swing.JTable();

    setBackground(new Color(143,190,0,25));
    setLayout(new java.awt.BorderLayout());

    panelPestanas.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N

    panelRegistroProduccion.setLayout(new java.awt.BorderLayout());

    panelNorteRegistro.setBackground(new Color(143,190,0,25));
    panelNorteRegistro.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 1, 10, 1));

    lblTituloRegistro.setFont(new java.awt.Font("Corbel", 1, 24)); // NOI18N
    lblTituloRegistro.setText("REGISTRO DE PRODUCCIÓN");
    panelNorteRegistro.add(lblTituloRegistro);

    panelRegistroProduccion.add(panelNorteRegistro, java.awt.BorderLayout.PAGE_START);

    panelCentroRegistro.setBackground(new Color(143,190,0,25));
    panelCentroRegistro.setBorder(javax.swing.BorderFactory.createEmptyBorder(30, 50, 50, 50));
    panelCentroRegistro.setLayout(new java.awt.BorderLayout());

    tablaRegistroProduccion.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {
        {new String(" "), new String(" "), new String(" ")},
              {new String(" "), new String(" "), new String(" ")},
              {new String(" "), new String(" "), new String(" ")},
              {new String(" "), new String(" "), new String(" ")},
              {new String(" "), new String(" "), new String(" ")},
              {new String(" "), new String(" "), new String(" ")},
              {new String(" "), new String(" "), new String(" ")},
              {new String(" "), new String(" "), new String(" ")},
              {new String(" "), new String(" "), new String(" ")},

      },
      new String [] {
        "NUMERO", "FECHA", "LECHE"
      }
    ) {
      Class[] types = new Class [] {
              Object.class, Object.class, Object.class
      };

      public Class getColumnClass(int columnIndex) {
        return types [columnIndex];
      }
    });
    panelTablaRegistro.setViewportView(tablaRegistroProduccion);

    panelCentroRegistro.add(panelTablaRegistro, java.awt.BorderLayout.CENTER);

    panelRegistroProduccion.add(panelCentroRegistro, java.awt.BorderLayout.CENTER);

    panelSurRegistro.setBackground(new Color(143,190,0,25));
    panelSurRegistro.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 40, 1));
    panelSurRegistro.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 5));

    btnRegistrar.setBackground(new Color(0, 168, 198, 135));
    btnRegistrar.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
    btnRegistrar.setForeground(new Color(255, 255, 255));
    btnRegistrar.setText("Registrar");
    panelSurRegistro.add(btnRegistrar);

    btnRegresarFromRegistro.setBackground(new Color(0, 168, 198, 135));
    btnRegresarFromRegistro.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
    btnRegresarFromRegistro.setForeground(new Color(255, 255, 255));
    btnRegresarFromRegistro.setText("Regresar");
    panelSurRegistro.add(btnRegresarFromRegistro);

    panelRegistroProduccion.add(panelSurRegistro, java.awt.BorderLayout.PAGE_END);

    panelPestanas.addTab("Registro", panelRegistroProduccion);

    panelConsultaProduccion.setLayout(new java.awt.BorderLayout());

    panelNorteConsulta.setBackground(new Color(143,190,0,25));
    panelNorteConsulta.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 1, 10, 1));
    panelNorteConsulta.setLayout(new java.awt.GridLayout(2, 0, 0, 10));

    lblTituloConsulta.setFont(new java.awt.Font("Corbel", 1, 24)); // NOI18N
    lblTituloConsulta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    lblTituloConsulta.setText("CONSULTAR PRODUCCION");
    panelNorteConsulta.add(lblTituloConsulta);

    panelInputs.setOpaque(false);

    lblFechaInicio.setFont(new java.awt.Font("Corbel", 1, 16)); // NOI18N
    lblFechaInicio.setText("Fecha inicio:");
    panelInputs.add(lblFechaInicio);

    txtFechaInicio.setColumns(8);
    txtFechaInicio.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
    panelInputs.add(txtFechaInicio);

    btnSelecFechaInicio.setBackground(new Color(0, 168, 198, 135));
    btnSelecFechaInicio.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
    btnSelecFechaInicio.setForeground(new Color(255, 255, 255));
    btnSelecFechaInicio.setText("Seleccionar");
    panelInputs.add(btnSelecFechaInicio);

    lblFechaCierre.setFont(new java.awt.Font("Corbel", 1, 16)); // NOI18N
    lblFechaCierre.setText("Fecha cierre:");
    panelInputs.add(lblFechaCierre);

    txtFechaCierre.setColumns(8);
    txtFechaCierre.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
    panelInputs.add(txtFechaCierre);

    btnSelecFechaCierre.setBackground(new Color(0, 168, 198, 135));
    btnSelecFechaCierre.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
    btnSelecFechaCierre.setForeground(new Color(255, 255, 255));
    btnSelecFechaCierre.setText("Seleccionar");
    panelInputs.add(btnSelecFechaCierre);

    panelNorteConsulta.add(panelInputs);

    panelConsultaProduccion.add(panelNorteConsulta, java.awt.BorderLayout.PAGE_START);

    panelSurConsulta.setBackground(new Color(143,190,0,25));
    panelSurConsulta.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 40, 5));
    panelSurConsulta.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 5));

    btnGenerar.setBackground(new Color(0, 168, 198, 135));
    btnGenerar.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
    btnGenerar.setForeground(new Color(255, 255, 255));
    btnGenerar.setText("Generar");
    panelSurConsulta.add(btnGenerar);

    btnRegresarFromConsulta.setBackground(new Color(0, 168, 198, 135));
    btnRegresarFromConsulta.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
    btnRegresarFromConsulta.setForeground(new Color(255, 255, 255));
    btnRegresarFromConsulta.setText("Regresar");
    panelSurConsulta.add(btnRegresarFromConsulta);

    panelConsultaProduccion.add(panelSurConsulta, java.awt.BorderLayout.PAGE_END);

    panelCentroConsulta.setBackground(new Color(143,190,0,25));
    panelCentroConsulta.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 40, 40, 40));
    panelCentroConsulta.setLayout(new java.awt.BorderLayout());

    tablaConsultaProduccion.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {
        {null, null},
        {null, null},
        {null, null},
        {null, null}
      },
      new String [] {
        "NUMERO", "LECHE"
      }
    ) {
      Class[] types = new Class [] {
        Byte.class, Integer.class
      };

      public Class getColumnClass(int columnIndex) {
        return types [columnIndex];
      }
    });
    panelTablaConsulta.setViewportView(tablaConsultaProduccion);

    panelCentroConsulta.add(panelTablaConsulta, java.awt.BorderLayout.CENTER);

    panelConsultaProduccion.add(panelCentroConsulta, java.awt.BorderLayout.CENTER);

    panelPestanas.addTab("Consulta", panelConsultaProduccion);

    add(panelPestanas, java.awt.BorderLayout.CENTER);
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnGenerar;
  private javax.swing.JButton btnRegistrar;
  private javax.swing.JButton btnRegresarFromConsulta;
  private javax.swing.JButton btnRegresarFromRegistro;
  private javax.swing.JButton btnSelecFechaCierre;
  private javax.swing.JButton btnSelecFechaInicio;
  private javax.swing.JLabel lblFechaCierre;
  private javax.swing.JLabel lblFechaInicio;
  private javax.swing.JLabel lblTituloConsulta;
  private javax.swing.JLabel lblTituloRegistro;
  private javax.swing.JPanel panelCentroConsulta;
  private javax.swing.JPanel panelCentroRegistro;
  private javax.swing.JPanel panelConsultaProduccion;
  private javax.swing.JPanel panelInputs;
  private javax.swing.JPanel panelNorteConsulta;
  private javax.swing.JPanel panelNorteRegistro;
  private javax.swing.JTabbedPane panelPestanas;
  private javax.swing.JPanel panelRegistroProduccion;
  private javax.swing.JPanel panelSurConsulta;
  private javax.swing.JPanel panelSurRegistro;
  private javax.swing.JScrollPane panelTablaConsulta;
  private javax.swing.JScrollPane panelTablaRegistro;
  private javax.swing.JTable tablaConsultaProduccion;
  private javax.swing.JTable tablaRegistroProduccion;
  private javax.swing.JTextField txtFechaCierre;
  private javax.swing.JTextField txtFechaInicio;
  // End of variables declaration//GEN-END:variables

  private ControladorDailyDairy controladorDailyDairy;
  public ControladorDailyDairy getControladorDailyDairy() {
    return controladorDailyDairy;
  }

  public void setControlador(ControladorDailyDairy controladorDailyDairy) {
    this.controladorDailyDairy = controladorDailyDairy;
    //this.b.addActionListener(this.controladorDailyDairy);
    this.btnRegresarFromRegistro.addActionListener(this.controladorDailyDairy);
    this.btnRegresarFromConsulta.addActionListener(this.controladorDailyDairy);
    this.btnRegistrar.addActionListener(this.controladorDailyDairy);

  }

  public JButton getBtnGenerar() {
    return btnGenerar;
  }

  public void setBtnGenerar(JButton btnGenerar) {
    this.btnGenerar = btnGenerar;
  }

  public JButton getBtnRegistrar() {
    return btnRegistrar;
  }

  public void setBtnRegistrar(JButton btnRegistrar) {
    this.btnRegistrar = btnRegistrar;
  }

  public JButton getBtnRegresarFromConsulta() {
    return btnRegresarFromConsulta;
  }

  public void setBtnRegresarFromConsulta(JButton btnRegresarFromConsulta) {
    this.btnRegresarFromConsulta = btnRegresarFromConsulta;
  }

  public JButton getBtnRegresarFromRegistro() {
    return btnRegresarFromRegistro;
  }

  public void setBtnRegresarFromRegistro(JButton btnRegresarFromRegistro) {
    this.btnRegresarFromRegistro = btnRegresarFromRegistro;
  }

  public JButton getBtnSelecFechaCierre() {
    return btnSelecFechaCierre;
  }

  public void setBtnSelecFechaCierre(JButton btnSelecFechaCierre) {
    this.btnSelecFechaCierre = btnSelecFechaCierre;
  }

  public JButton getBtnSelecFechaInicio() {
    return btnSelecFechaInicio;
  }

  public void setBtnSelecFechaInicio(JButton btnSelecFechaInicio) {
    this.btnSelecFechaInicio = btnSelecFechaInicio;
  }

  public JTable getTablaConsultaProduccion() {
    return tablaConsultaProduccion;
  }

  public void setTablaConsultaProduccion(JTable tablaConsultaProduccion) {
    this.tablaConsultaProduccion = tablaConsultaProduccion;
  }

  public JTable getTablaRegistroProduccion() {
    return tablaRegistroProduccion;
  }

  public void setTablaRegistroProduccion(JTable tablaRegistroProduccion) {
    this.tablaRegistroProduccion = tablaRegistroProduccion;
  }

  public JTextField getTxtFechaCierre() {
    return txtFechaCierre;
  }

  public void setTxtFechaCierre(JTextField txtFechaCierre) {
    this.txtFechaCierre = txtFechaCierre;
  }

  public JTextField getTxtFechaInicio() {
    return txtFechaInicio;
  }

  public void setTxtFechaInicio(JTextField txtFechaInicio) {
    this.txtFechaInicio = txtFechaInicio;
  }
}
