/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import controlador.ControladorDailyDairy;

import javax.swing.*;
import java.awt.Color;

/**
 *
 * @author Uriel Méndez Romero
 */
public class PanelInicio extends javax.swing.JPanel {

  /**
   * Creates new form PanelInicio
   */
  public PanelInicio() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    panelIzquierda = new javax.swing.JPanel();
    panelTitulo = new javax.swing.JPanel();
    lblTitulo1 = new javax.swing.JLabel();
    lblTitulo2 = new javax.swing.JLabel();
    panelDescripcion = new javax.swing.JPanel();
    lblDescripcion = new javax.swing.JLabel();
    panelBoton = new javax.swing.JPanel();
    btnGanado = new javax.swing.JButton();
    panelDerecha = new javax.swing.JPanel();
    lblImagen = new javax.swing.JLabel();

    setBorder(new javax.swing.border.LineBorder(new Color(255, 255, 255), 10, true));
    setMinimumSize(new java.awt.Dimension(720, 480));
    setName(""); // NOI18N
    setPreferredSize(new java.awt.Dimension(720, 480));
    setLayout(new java.awt.GridLayout(1, 2));

    panelIzquierda.setLayout(new java.awt.GridLayout(3, 0));

    panelTitulo.setBackground(new Color(143,190,0,170));
    panelTitulo.setBorder(javax.swing.BorderFactory.createEmptyBorder(50, 30, 10, 30));
    panelTitulo.setLayout(new java.awt.GridLayout(2, 0));

    lblTitulo1.setFont(new java.awt.Font("Corbel", 3, 42)); // NOI18N
    lblTitulo1.setForeground(new Color(255, 255, 255));
    lblTitulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    lblTitulo1.setText("BIENVENIDO A");
    lblTitulo1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
    panelTitulo.add(lblTitulo1);

    lblTitulo2.setFont(new java.awt.Font("Corbel", 3, 42)); // NOI18N
    lblTitulo2.setForeground(new Color(255, 255, 255));
    lblTitulo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    lblTitulo2.setText("DAILYDIARY!");
    lblTitulo2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
    panelTitulo.add(lblTitulo2);

    panelIzquierda.add(panelTitulo);

    panelDescripcion.setBackground(new Color(143,190,0,170));
    panelDescripcion.setBorder(javax.swing.BorderFactory.createEmptyBorder(30, 50, 30, 50));
    panelDescripcion.setLayout(new java.awt.BorderLayout());

    lblDescripcion.setFont(new java.awt.Font("Corbel", 0, 24)); // NOI18N
    lblDescripcion.setForeground(new Color(255, 255, 255));
    lblDescripcion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    lblDescripcion.setText("<html><body> <p>Sistema de gestión de ganadería de doble propósito </p></body></html>");
    lblDescripcion.setToolTipText("");
    panelDescripcion.add(lblDescripcion, java.awt.BorderLayout.CENTER);

    panelIzquierda.add(panelDescripcion);

    panelBoton.setBackground(new Color(143,190,0,170));
    panelBoton.setBorder(javax.swing.BorderFactory.createEmptyBorder(30, 30, 30, 30));

    btnGanado.setBackground(new Color(254, 254, 254));
    btnGanado.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
    btnGanado.setText("Ganado");
    btnGanado.setFocusPainted(false);
    btnGanado.setFocusable(false);
    btnGanado.setMargin(new java.awt.Insets(5, 18, 5, 18));
    panelBoton.add(btnGanado);

    panelIzquierda.add(panelBoton);

    add(panelIzquierda);

    panelDerecha.setBackground(new Color(143,190,0,170));
    panelDerecha.setLayout(new java.awt.BorderLayout());

    lblImagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    lblImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/menuCentro.png"))); // NOI18N
    panelDerecha.add(lblImagen, java.awt.BorderLayout.CENTER);

    add(panelDerecha);
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnGanado;
  private javax.swing.JLabel lblDescripcion;
  private javax.swing.JLabel lblImagen;
  private javax.swing.JLabel lblTitulo1;
  private javax.swing.JLabel lblTitulo2;
  private javax.swing.JPanel panelBoton;
  private javax.swing.JPanel panelDerecha;
  private javax.swing.JPanel panelDescripcion;
  private javax.swing.JPanel panelIzquierda;
  private javax.swing.JPanel panelTitulo;

  private ControladorDailyDairy controladorDailyDairy;
  public ControladorDailyDairy getControladorDailyDairy() {
    return controladorDailyDairy;
  }

  public void setControlador(ControladorDailyDairy controladorDailyDairy) {
    this.controladorDailyDairy = controladorDailyDairy;
    this.btnGanado.addActionListener(this.controladorDailyDairy);
  }

  public JButton getBtnGanado() {
    return this.btnGanado;
  }
  // End of variables declaration//GEN-END:variables
}
