/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import controlador.ControladorDailyDairy;

import javax.swing.*;
import java.awt.*;

/**
 * @author Uriel Méndez Romero
 */
public class PanelOrdena extends javax.swing.JPanel {

    /**
     * Creates new form PanelGanado
     */
    public PanelOrdena() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelIzquierda = new javax.swing.JPanel();
        btnAgregarOrdena = new javax.swing.JPanel();
        lblTituloAgregar = new javax.swing.JLabel();
        lblSubAgregar = new javax.swing.JLabel();
        btnEliminarOrdena = new javax.swing.JPanel();
        lblTituloEliminar = new javax.swing.JLabel();
        lblSubEliminar = new javax.swing.JLabel();
        btnListaOrdena = new javax.swing.JPanel();
        lblTituloListaOrdena = new javax.swing.JLabel();
        lblSubListaOrdena = new javax.swing.JLabel();
        btnMostrarProduccion = new javax.swing.JPanel();
        lblTituloMostrarProduccion = new javax.swing.JLabel();
        lblSubMostrarProduccion = new javax.swing.JLabel();
        panelDerecha = new javax.swing.JPanel();
        panelNorte = new javax.swing.JPanel();
        lblTituloOrdena = new javax.swing.JLabel();
        panelCentro = new javax.swing.JPanel();
        panelTablaOrdena = new javax.swing.JScrollPane();
        tablaOrdena = new javax.swing.JTable();
        panelSur = new javax.swing.JPanel();
        btnRegresar = new javax.swing.JButton();

        setBackground(new Color(254, 254, 254));
        setBorder(new javax.swing.border.LineBorder(new Color(255, 255, 255), 10, true));
        setLayout(new java.awt.BorderLayout(5, 5));

        panelIzquierda.setPreferredSize(new Dimension(240, 573));
        panelIzquierda.setBackground(new Color(143, 190, 0, 170));
        panelIzquierda.setBorder(javax.swing.BorderFactory.createEmptyBorder(40, 40, 40, 40));
        panelIzquierda.setLayout(new java.awt.GridLayout(4, 1, 20, 20));

        btnAgregarOrdena.setBackground(new Color(0, 168, 198, 135));
        btnAgregarOrdena.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAgregarOrdena.setLayout(new java.awt.GridLayout(2, 0));

        lblTituloAgregar.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        lblTituloAgregar.setForeground(new Color(255, 255, 255));
        lblTituloAgregar.setText("Agregar");
        lblTituloAgregar.setToolTipText("");
        lblTituloAgregar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lblTituloAgregar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        lblTituloAgregar.setFocusable(false);
        lblTituloAgregar.setPreferredSize(new java.awt.Dimension(62, 20));
        btnAgregarOrdena.add(lblTituloAgregar);

        lblSubAgregar.setFont(new java.awt.Font("Corbel", 0, 12)); // NOI18N
        lblSubAgregar.setForeground(new Color(255, 255, 255));
        lblSubAgregar.setText("<html><body>Agregar ganado a ordeña</body></html>");
        lblSubAgregar.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblSubAgregar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        lblSubAgregar.setFocusable(false);
        lblSubAgregar.setPreferredSize(new java.awt.Dimension(100, 18));
        btnAgregarOrdena.add(lblSubAgregar);

        panelIzquierda.add(btnAgregarOrdena);

        btnEliminarOrdena.setBackground(new Color(0, 168, 198, 135));
        btnEliminarOrdena.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEliminarOrdena.setLayout(new java.awt.GridLayout(2, 1));

        lblTituloEliminar.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        lblTituloEliminar.setForeground(new Color(255, 255, 255));
        lblTituloEliminar.setText("Eliminar");
        lblTituloEliminar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lblTituloEliminar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        lblTituloEliminar.setPreferredSize(new java.awt.Dimension(63, 20));
        btnEliminarOrdena.add(lblTituloEliminar);

        lblSubEliminar.setFont(new java.awt.Font("Corbel", 0, 12)); // NOI18N
        lblSubEliminar.setForeground(new Color(255, 255, 255));
        lblSubEliminar.setText("<html><body>Eliminar ganado de ordeña</body></html>");
        lblSubEliminar.setToolTipText("");
        lblSubEliminar.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblSubEliminar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        lblSubEliminar.setPreferredSize(new java.awt.Dimension(100, 18));
        btnEliminarOrdena.add(lblSubEliminar);

        panelIzquierda.add(btnEliminarOrdena);

        btnListaOrdena.setBackground(new Color(0, 168, 198, 135));
        btnListaOrdena.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnListaOrdena.setLayout(new java.awt.GridLayout(2, 1));

        lblTituloListaOrdena.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        lblTituloListaOrdena.setForeground(new Color(255, 255, 255));
        lblTituloListaOrdena.setText("Lista de ganado");
        lblTituloListaOrdena.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lblTituloListaOrdena.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        lblTituloListaOrdena.setPreferredSize(new java.awt.Dimension(123, 20));
        btnListaOrdena.add(lblTituloListaOrdena);

        lblSubListaOrdena.setFont(new java.awt.Font("Corbel", 0, 12)); // NOI18N
        lblSubListaOrdena.setForeground(new Color(255, 255, 255));
        lblSubListaOrdena.setText("<html><body>Genera una lista del ganado en ordeña </body></html>");
        lblSubListaOrdena.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblSubListaOrdena.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        lblSubListaOrdena.setPreferredSize(new java.awt.Dimension(100, 18));
        btnListaOrdena.add(lblSubListaOrdena);

        panelIzquierda.add(btnListaOrdena);

        btnMostrarProduccion.setBackground(new Color(0, 168, 198, 135));
        btnMostrarProduccion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMostrarProduccion.setLayout(new java.awt.GridLayout(2, 0));

        lblTituloMostrarProduccion.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        lblTituloMostrarProduccion.setForeground(new Color(255, 255, 255));
        lblTituloMostrarProduccion.setText("Mostrar producción");
        lblTituloMostrarProduccion.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lblTituloMostrarProduccion.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        btnMostrarProduccion.add(lblTituloMostrarProduccion);

        lblSubMostrarProduccion.setFont(new java.awt.Font("Corbel", 0, 12)); // NOI18N
        lblSubMostrarProduccion.setForeground(new Color(255, 255, 255));
        lblSubMostrarProduccion.setText("Mostar interfaz de producción");
        lblSubMostrarProduccion.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblSubMostrarProduccion.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        btnMostrarProduccion.add(lblSubMostrarProduccion);

        panelIzquierda.add(btnMostrarProduccion);

        add(panelIzquierda, java.awt.BorderLayout.LINE_START);

        panelDerecha.setLayout(new java.awt.BorderLayout());

        panelNorte.setBackground(new Color(143, 190, 0, 25));
        panelNorte.setBorder(javax.swing.BorderFactory.createEmptyBorder(40, 20, 20, 20));

        lblTituloOrdena.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        lblTituloOrdena.setText("ORDEÑA");
        panelNorte.add(lblTituloOrdena);

        panelDerecha.add(panelNorte, java.awt.BorderLayout.PAGE_START);

        panelCentro.setBackground(new Color(143, 190, 0, 25));
        panelCentro.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 40, 40, 40));
        panelCentro.setLayout(new java.awt.BorderLayout());

        tablaOrdena.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{
                        /*{null, null, null, null, null},
                        {null, null, null, null, null},
                        {null, null, null, null, null},
                        {null, null, null, null, null}*/
                },
                new String[]{
                        "NUMERO", "FIERRO", "COLOR", "RAZA", "CRIA"
                }
        ) {
            Class[] types = new Class[]{
                    String.class, String.class, String.class, String.class, String.class
            };
//      boolean[] canEdit = new boolean [] {
//        false, false, false, false, false
//      };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

//      public boolean isCellEditable(int rowIndex, int columnIndex) {
//        return canEdit [columnIndex];
//      }
        });
        panelTablaOrdena.setViewportView(tablaOrdena);

        panelCentro.add(panelTablaOrdena, java.awt.BorderLayout.CENTER);

        panelDerecha.add(panelCentro, java.awt.BorderLayout.CENTER);

        panelSur.setBackground(new Color(143, 190, 0, 25));
        panelSur.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 20, 1));

        btnRegresar.setBackground(new Color(0, 168, 198, 135));
        btnRegresar.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        btnRegresar.setForeground(new Color(255, 255, 255));
        btnRegresar.setText("Regresar");
        btnRegresar.setFocusPainted(false);
        btnRegresar.setFocusable(false);
        btnRegresar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRegresar.setMargin(new java.awt.Insets(4, 14, 4, 14));
        panelSur.add(btnRegresar);

        panelDerecha.add(panelSur, java.awt.BorderLayout.SOUTH);

        add(panelDerecha, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnAgregarOrdena;
    private javax.swing.JPanel btnEliminarOrdena;
    private javax.swing.JPanel btnListaOrdena;
    private javax.swing.JPanel btnMostrarProduccion;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel lblSubAgregar;
    private javax.swing.JLabel lblSubEliminar;
    private javax.swing.JLabel lblSubListaOrdena;
    private javax.swing.JLabel lblSubMostrarProduccion;
    private javax.swing.JLabel lblTituloAgregar;
    private javax.swing.JLabel lblTituloEliminar;
    private javax.swing.JLabel lblTituloListaOrdena;
    private javax.swing.JLabel lblTituloMostrarProduccion;
    private javax.swing.JLabel lblTituloOrdena;
    private javax.swing.JPanel panelCentro;
    private javax.swing.JPanel panelDerecha;
    private javax.swing.JPanel panelIzquierda;
    private javax.swing.JPanel panelNorte;
    private javax.swing.JPanel panelSur;
    private javax.swing.JScrollPane panelTablaOrdena;
    private javax.swing.JTable tablaOrdena;
    // End of variables declaration//GEN-END:variables

    private ControladorDailyDairy controladorDailyDairy;

    public ControladorDailyDairy getControladorDailyDairy() {
        return controladorDailyDairy;
    }

    public void setControlador(ControladorDailyDairy controladorDailyDairy) {
        this.controladorDailyDairy = controladorDailyDairy;
        this.btnRegresar.addActionListener(this.controladorDailyDairy);
        this.lblSubAgregar.addMouseListener(this.controladorDailyDairy);
        this.lblTituloAgregar.addMouseListener(this.controladorDailyDairy);
        this.btnAgregarOrdena.addMouseListener(this.controladorDailyDairy);
        this.lblSubMostrarProduccion.addMouseListener(this.controladorDailyDairy);
        this.lblTituloMostrarProduccion.addMouseListener(this.controladorDailyDairy);
        this.btnMostrarProduccion.addMouseListener(this.controladorDailyDairy);
    }

    public JButton getBtnRegresar() {
        return this.btnRegresar;
    }

    public JPanel getBtnAgregarOrdena() {
        return btnAgregarOrdena;
    }

    public void setBtnAgregarOrdena(JPanel btnAgregarOrdena) {
        this.btnAgregarOrdena = btnAgregarOrdena;
    }

    public JPanel getBtnEliminarOrdena() {
        return btnEliminarOrdena;
    }

    public void setBtnEliminarOrdena(JPanel btnEliminarOrdena) {
        this.btnEliminarOrdena = btnEliminarOrdena;
    }

    public JPanel getBtnListaOrdena() {
        return btnListaOrdena;
    }

    public void setBtnListaOrdena(JPanel btnListaOrdena) {
        this.btnListaOrdena = btnListaOrdena;
    }

    public JPanel getBtnMostrarProduccion() {
        return btnMostrarProduccion;
    }

    public void setBtnMostrarProduccion(JPanel btnMostrarProduccion) {
        this.btnMostrarProduccion = btnMostrarProduccion;
    }

    public void setBtnRegresar(JButton btnRegresar) {
        this.btnRegresar = btnRegresar;
    }

    public JTable getTablaOrdena() {
        return tablaOrdena;
    }

    public void setTablaOrdena(JTable tablaOrdena) {
        this.tablaOrdena = tablaOrdena;
    }

    public JLabel getLblSubAgregar() {
        return lblSubAgregar;
    }

    public void setLblSubAgregar(JLabel lblSubAgregar) {
        this.lblSubAgregar = lblSubAgregar;
    }

    public JLabel getLblSubEliminar() {
        return lblSubEliminar;
    }

    public void setLblSubEliminar(JLabel lblSubEliminar) {
        this.lblSubEliminar = lblSubEliminar;
    }

    public JLabel getLblSubListaOrdena() {
        return lblSubListaOrdena;
    }

    public void setLblSubListaOrdena(JLabel lblSubListaOrdena) {
        this.lblSubListaOrdena = lblSubListaOrdena;
    }

    public JLabel getLblSubMostrarProduccion() {
        return lblSubMostrarProduccion;
    }

    public void setLblSubMostrarProduccion(JLabel lblSubMostrarProduccion) {
        this.lblSubMostrarProduccion = lblSubMostrarProduccion;
    }

    public JLabel getLblTituloAgregar() {
        return lblTituloAgregar;
    }

    public void setLblTituloAgregar(JLabel lblTituloAgregar) {
        this.lblTituloAgregar = lblTituloAgregar;
    }

    public JLabel getLblTituloEliminar() {
        return lblTituloEliminar;
    }

    public void setLblTituloEliminar(JLabel lblTituloEliminar) {
        this.lblTituloEliminar = lblTituloEliminar;
    }

    public JLabel getLblTituloListaOrdena() {
        return lblTituloListaOrdena;
    }

    public void setLblTituloListaOrdena(JLabel lblTituloListaOrdena) {
        this.lblTituloListaOrdena = lblTituloListaOrdena;
    }

    public JLabel getLblTituloMostrarProduccion() {
        return lblTituloMostrarProduccion;
    }

    public void setLblTituloMostrarProduccion(JLabel lblTituloMostrarProduccion) {
        this.lblTituloMostrarProduccion = lblTituloMostrarProduccion;
    }
}
