/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import java.awt.Color;

/**
 *
 * @author Uriel Méndez Romero
 */
public class PanelVenta extends javax.swing.JPanel {

  /**
   * Creates new form PanelVenta
   */
  public PanelVenta() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    panelNorte = new javax.swing.JPanel();
    lblTituloVenta = new javax.swing.JLabel();
    jPanel4 = new javax.swing.JPanel();
    lblFecha = new javax.swing.JLabel();
    txtFecha = new javax.swing.JTextField();
    btnFecha = new javax.swing.JButton();
    lblPrecio = new javax.swing.JLabel();
    txtPrecio = new javax.swing.JTextField();
    panelSur = new javax.swing.JPanel();
    panelSurBotones = new javax.swing.JPanel();
    btnAceptar = new javax.swing.JButton();
    btnRegresar = new javax.swing.JButton();
    panelSurImporte = new javax.swing.JPanel();
    lblImporte = new javax.swing.JLabel();
    txtImporte = new javax.swing.JTextField();
    panelCentro = new javax.swing.JPanel();
    panelDatos = new javax.swing.JPanel();
    lblDatosGanado = new javax.swing.JLabel();
    lblDatosComprador = new javax.swing.JLabel();
    panelInputs = new javax.swing.JPanel();
    lblNumero = new javax.swing.JLabel();
    lblNombre = new javax.swing.JLabel();
    panelNumero = new javax.swing.JPanel();
    txtNumero = new javax.swing.JTextField();
    panelNombre = new javax.swing.JPanel();
    txtNombre = new javax.swing.JTextField();
    lblPeso = new javax.swing.JLabel();
    lblNumeroTelefonico = new javax.swing.JLabel();
    panelPeso = new javax.swing.JPanel();
    txtPeso = new javax.swing.JTextField();
    panelNumeroTelefonico = new javax.swing.JPanel();
    txtNumeroTelefonico = new javax.swing.JTextField();

    setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 10));
    setLayout(new java.awt.BorderLayout());

    panelNorte.setBackground(new Color(143,190,0,25));
    panelNorte.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 1, 1, 1));
    panelNorte.setLayout(new java.awt.GridLayout(2, 0, 0, 10));

    lblTituloVenta.setFont(new java.awt.Font("Corbel", 1, 24)); // NOI18N
    lblTituloVenta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    lblTituloVenta.setText("VENTA");
    panelNorte.add(lblTituloVenta);

    jPanel4.setOpaque(false);

    lblFecha.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
    lblFecha.setText("Fecha:");
    jPanel4.add(lblFecha);

    txtFecha.setColumns(8);
    jPanel4.add(txtFecha);

    btnFecha.setBackground(new Color(0, 168, 198, 135));
    btnFecha.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
    btnFecha.setForeground(new java.awt.Color(255, 255, 255));
    btnFecha.setText("Seleccionar");
    jPanel4.add(btnFecha);

    lblPrecio.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
    lblPrecio.setText("         Precio por Kg:");
    jPanel4.add(lblPrecio);

    txtPrecio.setColumns(6);
    jPanel4.add(txtPrecio);

    panelNorte.add(jPanel4);

    add(panelNorte, java.awt.BorderLayout.PAGE_START);

    panelSur.setBackground(new Color(143,190,0,25));
    panelSur.setLayout(new java.awt.BorderLayout());

    panelSurBotones.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 1, 20, 1));
    panelSurBotones.setOpaque(false);
    panelSurBotones.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 5));

    btnAceptar.setBackground(new Color(0, 168, 198, 135));
    btnAceptar.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
    btnAceptar.setForeground(new java.awt.Color(255, 255, 255));
    btnAceptar.setText("Aceptar");
    panelSurBotones.add(btnAceptar);

    btnRegresar.setBackground(new Color(0, 168, 198, 135));
    btnRegresar.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
    btnRegresar.setForeground(new java.awt.Color(255, 255, 255));
    btnRegresar.setText("Regresar");
    panelSurBotones.add(btnRegresar);

    panelSur.add(panelSurBotones, java.awt.BorderLayout.PAGE_END);

    panelSurImporte.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 1, 5, 1));
    panelSurImporte.setOpaque(false);

    lblImporte.setFont(new java.awt.Font("Corbel", 1, 16)); // NOI18N
    lblImporte.setText("Importe:");
    panelSurImporte.add(lblImporte);

    txtImporte.setEditable(false);
    txtImporte.setColumns(6);
    txtImporte.setPreferredSize(new java.awt.Dimension(80, 30));
    panelSurImporte.add(txtImporte);

    panelSur.add(panelSurImporte, java.awt.BorderLayout.CENTER);

    add(panelSur, java.awt.BorderLayout.PAGE_END);

    panelCentro.setBackground(new Color(143,190,0,25));
    panelCentro.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 60, 10, 60));
    panelCentro.setLayout(new java.awt.BorderLayout());

    panelDatos.setOpaque(false);
    panelDatos.setLayout(new java.awt.GridLayout(1, 2, 80, 0));

    lblDatosGanado.setFont(new java.awt.Font("Corbel", 1, 16)); // NOI18N
    lblDatosGanado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    lblDatosGanado.setText("DATOS DEL GANADO");
    panelDatos.add(lblDatosGanado);

    lblDatosComprador.setFont(new java.awt.Font("Corbel", 1, 16)); // NOI18N
    lblDatosComprador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    lblDatosComprador.setText("DATOS DEL COMPRADOR");
    panelDatos.add(lblDatosComprador);

    panelCentro.add(panelDatos, java.awt.BorderLayout.PAGE_START);

    panelInputs.setOpaque(false);
    panelInputs.setLayout(new java.awt.GridLayout(4, 2, 80, 5));

    lblNumero.setFont(new java.awt.Font("Corbel", 1, 16)); // NOI18N
    lblNumero.setText("Numero del ganado");
    lblNumero.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
    panelInputs.add(lblNumero);

    lblNombre.setFont(new java.awt.Font("Corbel", 1, 16)); // NOI18N
    lblNombre.setText("Nombre");
    lblNombre.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
    panelInputs.add(lblNombre);

    panelNumero.setOpaque(false);
    panelNumero.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 5));

    txtNumero.setColumns(20);
    txtNumero.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
    txtNumero.setPreferredSize(new java.awt.Dimension(234, 30));
    panelNumero.add(txtNumero);

    panelInputs.add(panelNumero);

    panelNombre.setOpaque(false);
    panelNombre.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 5));

    txtNombre.setColumns(20);
    txtNombre.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
    txtNombre.setPreferredSize(new java.awt.Dimension(234, 30));
    panelNombre.add(txtNombre);

    panelInputs.add(panelNombre);

    lblPeso.setFont(new java.awt.Font("Corbel", 1, 16)); // NOI18N
    lblPeso.setText("Peso del ganado");
    lblPeso.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
    lblPeso.setPreferredSize(new java.awt.Dimension(113, 15));
    panelInputs.add(lblPeso);

    lblNumeroTelefonico.setFont(new java.awt.Font("Corbel", 1, 16)); // NOI18N
    lblNumeroTelefonico.setText("Numero telefonico");
    lblNumeroTelefonico.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
    panelInputs.add(lblNumeroTelefonico);

    panelPeso.setOpaque(false);
    panelPeso.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 5));

    txtPeso.setColumns(20);
    txtPeso.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
    txtPeso.setPreferredSize(new java.awt.Dimension(234, 30));
    panelPeso.add(txtPeso);

    panelInputs.add(panelPeso);

    panelNumeroTelefonico.setOpaque(false);
    panelNumeroTelefonico.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 5));

    txtNumeroTelefonico.setColumns(20);
    txtNumeroTelefonico.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
    txtNumeroTelefonico.setPreferredSize(new java.awt.Dimension(234, 30));
    panelNumeroTelefonico.add(txtNumeroTelefonico);

    panelInputs.add(panelNumeroTelefonico);

    panelCentro.add(panelInputs, java.awt.BorderLayout.CENTER);

    add(panelCentro, java.awt.BorderLayout.CENTER);
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnAceptar;
  private javax.swing.JButton btnFecha;
  private javax.swing.JButton btnRegresar;
  private javax.swing.JPanel jPanel4;
  private javax.swing.JLabel lblDatosComprador;
  private javax.swing.JLabel lblDatosGanado;
  private javax.swing.JLabel lblFecha;
  private javax.swing.JLabel lblImporte;
  private javax.swing.JLabel lblNombre;
  private javax.swing.JLabel lblNumero;
  private javax.swing.JLabel lblNumeroTelefonico;
  private javax.swing.JLabel lblPeso;
  private javax.swing.JLabel lblPrecio;
  private javax.swing.JLabel lblTituloVenta;
  private javax.swing.JPanel panelCentro;
  private javax.swing.JPanel panelDatos;
  private javax.swing.JPanel panelInputs;
  private javax.swing.JPanel panelNombre;
  private javax.swing.JPanel panelNorte;
  private javax.swing.JPanel panelNumero;
  private javax.swing.JPanel panelNumeroTelefonico;
  private javax.swing.JPanel panelPeso;
  private javax.swing.JPanel panelSur;
  private javax.swing.JPanel panelSurBotones;
  private javax.swing.JPanel panelSurImporte;
  private javax.swing.JTextField txtFecha;
  private javax.swing.JTextField txtImporte;
  private javax.swing.JTextField txtNombre;
  private javax.swing.JTextField txtNumero;
  private javax.swing.JTextField txtNumeroTelefonico;
  private javax.swing.JTextField txtPeso;
  private javax.swing.JTextField txtPrecio;
  // End of variables declaration//GEN-END:variables
}
